(defun compMatrix(matriz)
  (if (null matriz)
    0
    (+ 1 (compMatrix (cdr matriz)))))


(defun espacoembranco(m x y)
    (if (and (= x 0) (= y 0))
        (return-from espacoembranco (list -1 -1))
        (if (= y 0)
            (if (= 0 (nth (- x 1) (nth (- (compMatrix m) 1) m)))
                (return-from espacoembranco (list (- x 1) (- (compMatrix m) 1)))
                (return-from espacoembranco  (espacoembranco m (- x 1) (- (compMatrix m) 1)))
           )
        )
    )
    (if (= x 0)
        (if (= 0 (nth 0 (nth (- y 1) m)))
            (return-from espacoembranco (list 0 (- y 1)))
            (return-from espacoembranco  (espacoembranco m x (- y 1)))
        )
        (if (= 0 (nth x (nth (- y 1) m)))
            (return-from espacoembranco (list x (- y 1)))
           (return-from espacoembranco  (espacoembranco m x (- y 1)))
        )
    )
)
(setf ma(list '(1 1 0 2 2 5 5)
          '(1 1 3 4 4 6 5)
          '(1 1 4 4 8 6 6)
          '(7 4 4 8 8 9 6)
          '(7 7 8 8 9 9 12)
          '(10 10 10 9 9 9 12)
          '(11 10 10 12 12 12 12)
       )
)

(print (espacoembranco ma 4 2))